# Generated by Django 4.0.2 on 2022-02-16 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0.0, verbose_name='Бюджет')),
                ('revenue', models.FloatField(blank=True, default=0.0, verbose_name='Доход')),
                ('consumption', models.FloatField(blank=True, default=0.0, verbose_name='Расход')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата транзакции')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
    ]
