# Generated by Django 4.0.2 on 2022-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default='Операция', max_length=100, verbose_name='Название транзакции'),
        ),
    ]
