# Generated by Django 4.0.2 on 2022-02-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontrol', '0003_alter_budget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название транзакции'),
        ),
    ]
