# Generated by Django 4.0.2 on 2022-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontrol', '0004_alter_budget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='revenue',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Стоимость'),
        ),
    ]
