# Generated by Django 4.0.2 on 2022-02-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycontrol', '0005_alter_budget_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='revenue',
        ),
    ]
